name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set git config
      run: |
        git config --local user.email "yoshihiro503@proofcafe.org"
        git config --local user.name "yoshihiro503"

    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - run: git fetch && git merge --allow-unrelated-histories origin/master

    - uses: actions/setup-node@v1
    - run: rm -rf node_modules && yarn install && yarn build

    - name: Commit and Push
      run: |
        git add .
        git commit -m Update
        git push origin gh-pages
