name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set git config
      run: |
        git config --local user.email "yoshihiro503@proofcafe.org"
        git config --local user.name "yoshihiro503"
    - name: Merge master branch
      run: |
        git fetch --unshallow origin gh-pages
        git checkout gh-pages
        git merge master

    - uses: actions/setup-node@v1
    - run: rm -rf node_modules && yarn install && yarn build

    - name: Commit and Push
      run: |
        npm install -g --silent gh-pages
        gh-pages --message "[skip ci] Updated" --dist . --dest .
